### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by mariobarretta** [helloideabox/elementor-widget-manager#1]
Your work and idea is genail but a lot of people's asking if hiddening the widget we also do not have the code of widget in our site.
All hope that also the code there is not but no one has understood if your plugin only hidden or if do other or if you have planned to can add also this feature

**Comment by nirbhay18** [comment]
Hi @mariobarretta,

The plugin prevents the widget code from getting loaded, not just hide it.

**Comment by mariobarretta** [comment]
> Hi @mariobarretta,
> 
> The plugin prevents the widget code from getting loaded, not just hide it.

Hi @nirbhay18 
really Thank You for your reply.
So we can use your great plugin having als an added benefit about to not have all not used code in our elementor projects? 

Thank you for your time and help and work
